### ISSUE TITLE
Backend feature requests

### ISSUE THREAD

**Issue by jbcm627** [cubing/wca-website#14]
A list of some things that should be implemented backend, in addition to what exists in the php system.  Not that I think the workflow should necessarily be the same - the fewer steps the better - these are just things to keep in mind.

 - [ ] Edit competitor country
 - [ ] Birthdate checks when uploading results

...I may try to aggregate more here eventually.  See also:
https://github.com/cubing/wca-website-php/issues?q=is%3Aopen+is%3Aissue+label%3A%22Feature+Request%22

**Comment by lgarron** [comment]
How about just making an issue for each thing and creating a `backend` label (so you can just search for `backend` and `enhancement`)

**Comment by jbcm627** [comment]
Yeah... that might be a good idea.  I'd like to see what is going to happen before opening a ton of tickets though.  Right now I don't know what is planned beyond these:
https://github.com/cubing/wca-website/search?q=todo

**Comment by SAuroux** [comment]
As I didn't see a backend label yet I'm just going to post this here:

It happens quite often that competitors end up with multiple accounts, most of the time because they don't enter their WCA ID upon registration. Once they have multiple accounts it is quite annoying to merge them in the database.

As a result I would like to see a script for this, which could look as follows:

"Please enter the WCA IDs you want to merge. Both profiles will be merged into id1."

id1: __________ id2: __________

Code: 
UPDATE `Results` SET personId=id1 WHERE personId=id2;
DELETE FROM `Persons`WHERE id=id2

**Comment by jfly** [comment]
@Luis-J-Ianez has made some improvements to the WA relating to birthdays: https://github.com/cubing/wca-workbook-assistant/pull/108. This is a great thing to have now, but I agree that in the fullness of time we should have the wca website protecting itself.
