### ISSUE TITLE
Things we don't actually need

### ISSUE THREAD

**Issue by lgarron** [cubing/wca-website#3]
Here is a brutally honest list of things that I think are not important enough for the site overhaul (#1). We can add back any of them once the basic stuff is there, but I think we can survive without them.

This list will be controversial, but hopefully it will get everyone on the same page.

- Drupal stories (competition announcements)
- Results Statistics
- Support for old browsers
  - As long as it's readable in IE 8 (or below), I don't care how it looks.

**Comment by jfly** [comment]
On December 22, 2014, Baiqiang did some analysis of how often certain parts of the website are *actually* used:

I've done some analysis based on the Google Analytics. Only the top 20,000 pages were counted, from May 26, 2013 to Dec 20 2024. The following table lists visits of each page on the results section. The detail data is attached as an excel file. The pages/views who have a visit percent lower than 1.5% were colored in orange.

Page                     |  Visits |  Percent
-------------------------|---------|---------
competition              | 2477770 | 26.19%
p                        | 2370465 | 25.06%
events                   | 2282717 | 24.13%
competitions             | 1171126 | 12.38%
regions                  |  536267 |  5.67%
persons                  |  392650 |  4.15%
statistics               |   68334 |  0.72%
misc                     |   44917 |  0.47%
index                    |   41465 |  0.44%
media                    |   31231 |  0.33%
competition_edit         |   30547 |  0.32%
person_set               |   11198 |  0.12%
media_insertion          |     515 |  0.01%
person_map               |     397 |  0.00%
registration_information |     131 |  0.00%
test                     |      60 |  0.00%
map_coords               |      47 |  0.00%

As James said, some features have very low visits. We may remove these or leave them in the future. I think the following views can be removed.

1) The "Years" and "Show" selection on the rankings page. For the "Years", "Until Some Year" and Only Some Year" totally have only 1.77% visits. For the "Show", I prefer to make a pagination.
2) The "Map" button and "Event" selection on the competitions page. They all have low visits. Listing competitions which contain special event will reduce the performance because of the REGEXP in the sql.
3) The "Years" selection, "Slim" button and "Separate" button on the records page. The "Slim" and "Separate" view only show the same content with the "Mixed" view in another format. I don't think they are necessary.
